remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Skye Zhong Digital Scholarship Summer Fellows Program

description: May 30-August 4, 2023, at Bryn Mawr College

author: Skye Zhong

markdown: kramdown

encoding: UTF-8

domain: digbmc.github.io
url: https://digbmc.github.io
baseurl: /dssf-syll

exclude:
  - README.md
  - LICENSE
  - scraps.md

collections:
  weeks:
    output: true
